- config.go
- config_test.go
- handler.go
- handler_test.go
- main.go
This PR:
- Ensures alphabetical ordering in the YAML configuration
- Uses a pointer value for the `Config` in various places
- Adds a new test
- Removes the import comment which would not allow external builds
Closes #20
> Enforce alphabetical ordering of packages in YAML config

- .dockerignore
- Dockerfile
- Dockerfile.sally
- Makefile
- glide.lock
- glide.yaml
- utils_test.go
This PR does a few things:
- Adds a development Dockerfile
`Dockerfile` defines a Docker image that can be used for development and for building the production Docker image. This gives a clean state to run development commands in - `make docker-test` should effectively be the SOT for whether or not sally is passing. This is useful in a lot of scenarios - perhaps something was added that was not vendored properly, or one of the linting binaries was compiled on a development branch and is out of date, or anything else. It also makes it possible to drop this repository into Elastic Beanstalk (this is how https://github.com/peter-edge/importserver-go is deployed). Also, it gives a clean environment to compile the production Docker image in - when go panics, it will show the filepaths to files …
> Add dockerfiles and update makefile

- CHANGELOG.md
- README.md
- config.go
- config_test.go
- handler_test.go
Update our default Godoc server from `https://godoc.org` to the shiny, new `https://pkg.go.dev/`
Closes #39, T4832833
> Update Godoc server to pkg.go.dev

- .github/workflows/go.yml
- Dockerfile
sally is not a library, so there's no reason to test it with two
versions of Go.
Use the latest version of Go to build and test it.
> Use Go 1.17 to test and build

- templates/index.html
When we originally switched to pkg.go.dev (#40),
it did not offer documentation badges so we relied on a third-party
service.
That's no longer true (https://pkg.go.dev/badge) so we can use
pkg.go.dev's more "on-brand" badges for this.
Screenshot:
> badge: Use pkg.go.dev badge

- .github/workflows/go.yml
- config.go
- templates/templates.go
This updates sally to build and test against Go 1.19.
Additionally, this upgrades the GitHub Action versions
for checkout and setup-go.
One of the features in setup-go v3 is that caching is built-in
and opted-into with `cache: true`.
Non-CI changes: gofmt, drop ioutil
> ci: Use Go 1.19 and update GH actions

- README.md
Adds more details on how to configure sally
and what the required and optional fields are.
Also updates the installation instructions
since you can't `go get` the binary anymore.
> README: Document configuration further

- utils_test.go
Since upgrading to Go 1.19 we are seeing linter error due to usage of the deprecated io/ioutil package.
This removes the usage of io/ioutil package.
> Fix lint error issues

- config.go
- config_test.go
The configuration parser requries that
entries in the 'packages' section
are in alphabetical order.
It will fail parsing if that's not the case,
even if the configuration is otherwise valid.
This seems like an unnecessary artificial limitation.
Enforcing such a convention should be the user's choice.
This change deletes this limitation.
---
Feel free to close if you feel that this restriction adds value.
> config: Don't require packages to be alphabetical

- CHANGELOG.md
- templates/index.html
Instead of using a table, take advantage of the grid layout.
We still print a table of sorts,
but it's more fluid in appearance based on width of the screen.
On narrower screens, we'll show a listing
where each item has a description label next to it
rather than at the top.
---
**Demo**
Before:
[before.webm](https://user-images.githubusercontent.com/41730/213947951-9a5732d7-bad2-4037-9a20-659acf5aa471.webm)
After:
[after.webm](https://user-images.githubusercontent.com/41730/213947966-cad30ca0-2946-4c16-81af-8c037a3c9053.webm)
> template: Use a more fluid layout

- CHANGELOG.md
- README.md
- config.go
- handler_test.go
- sally.yaml
- templates/index.html
Packages may now optionally specify a description.
If specified, this is printed below the package information,
indented one column to make it stand out.
Depends on #67
---
Preview:
Resizing:
[description.webm](https://user-images.githubusercontent.com/41730/213948849-55201550-f8d0-4436-81ea-28e977a2c3e1.webm)
---
This change is stacked on top of #67.
It will show a duplicate commit until that PR is merged and this is rebased.
> Add support for package descriptions

- go.mod
- go.sum
- utils_test.go
This dependency is used to format and compare HTML.
An additional dependency isn't needed;
we can use the existing (previously transitive) x/net package
to reformat and compare the HTML.
> Drop gohtml dependency

- go.mod
- go.sum
- handler.go
- handler_test.go
This drops the third-party HTTP router dependency.
This dependency wasn't strictly necessary
since our routing needs are quite basic:
- `/$name` and `/$name/*` for all registered packages
- `/` for root
This is easily accomplished with `http.ServeMux`:
- register `/$name` and `/$name/`.
The latter will receive all subpackage requests.
- register `/` and reject anything that isn't for exactly `/`.
> Drop httprouter dependency

- Dockerfile
Adds a Dockerfile that builds sally using a phased Docker build.
The first phase builds sally,
and the second phase publishes a scratch image
with just sally.
If Uber publishes this to a container registry,
a user can use it like so:
% vim sally.yaml # create a sally yaml
% cat > Dockerfile
FROM sally:latest
COPY sally.yaml /sally.yaml
% docker build .
Even without publishing, this provides an example
of how to build sally for deployment.
Testing:
I verified the instructions above locally
by tagging locally with:
% docker build -t sally:latest
I'm also using a variation of this Dockerfile in production
right now for my own hosted instance of sally.
> Add minimal Dockerfile

- CHANGELOG.md
Release notes for v1.3.0 had an incorrect link for changes included in v1.3.0; fixing this before we actually tag a release with this.
> Fix typo on release notes

- .github/workflows/docker.yml
- .github/workflows/go.yml
- README.md
Adds a workflow that builds and publishes a Docker image
to ghcr.io based on the Dockerfile in the root of the repository.
This will become available at
https://github.com/uber-go/sally/pkgs/container/sally.
Users will be able to import it by using `ghcr.io/uber-go/sally:$tag`
with `docker pull` or in the `FROM` clause of their own Docker file.
As a test for this, I published it manually to my own fork.
The image is at https://github.com/abhinav/sally/pkgs/container/sally.
With that, I ran the following Dockerfile:
FROM ghcr.io/abhinav/sally:master
COPY sally.yaml /
And it worked as expected.
Based on instructions at
https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
with help from …
> ci: Publish Docker image to ghcr.io on release

- config.go
- config_test.go
- handler.go
- handler_test.go
Renames the Package struct to PackageConfig
to make it clear that it is a configuration struct.
This differentiation will help disconnect
the configuration-level representation
from the runtime representation of this information.
This patch also adds documentation to the config package
that was previously missing.
> config: Rename Package to PackageConfig, add docs

- handler.go
This patch removes the need to retain the configuration in the
packageHandler struct.
Instead, it retains only the fields that are required for the
handler to function.
This also allows us to pre-compute the canonical import path
rather than calculating it on the request path.
> refactor(packageHandler): Don't retain configuration

- handler.go
- templates/index.html
Similar to the previous patch,
this patch removes knowledge of the configuration from the index handler.
Instead, the index handler is now passed a list of packageInfo structs
each containing just the information needed to render the index page.
This also obviates the need to duplicate the logic to compute
the package import path in the index.html template.
> refactor(indexHandler): Don't retain configuration

- .github/workflows/fossa.yaml
- .github/workflows/go.yml
Updates the checkout, setup-go, and codecov GitHub Actions.
Supersedes #88, #89, #90
> ci: Update actions

- .github/workflows/fossa.yaml
Update fossa action to v1.1.0
The FOSSA check has been failing for a while with
fossa-actions@v1 Error: Input required and not supplied: api-key
This has caused the dependabot queue to backup, we also can't merge them
manually in sally because this check is required.
Updating the version seems to cause the check to run successfully again.
Other repositories have run into the same issue
ref: https://github.com/getsentry/self-hosted/issues/1351
> Update fossa action to v1.1.0

- templates/index.html
Fixes the documentation URL in the homepage, as it already includes the protocol:
https://github.com/uber-go/sally/blob/686fb8782cfa89a807ecc6dcbc104c6dab43eb66/handler.go#L45
> fix: documentation URL in index page

- config.go
- config_test.go
- handler.go
- templates/index.html
- templates/package.html
Adds support to other VCS systems as per the specification. Defaults to `git` for backwards compatibility. Also renamed the internally used `.GitURL` to `.RepoURL` for clarity.
> feat: add support for other vcs systems

- .github/workflows/go.yml
Following https://github.com/uber-go/zap/pull/1424 and https://github.com/uber-go/fx/pull/1185 as examples.
`--version` is no longer accepted. Use `--help` instead.
> CI: Fix golangci-lint installation step

- .github/workflows/go.yml
Adds codecov token as required by codecov-action v4.
> CI: Use codecov token
